#161883389 Build the update feature where you can update status
Bakley/SendIT-Api-V1 pull request #5
Opened 2018-11-13 06:44 UTC by Bakley

### What does this PR do?
Build the PUT method to update status

### Description of Task to be completed?
Has the following API Endpoints working:

`PUT api/v1/parcel/<id>/cancel`

### How should this be manually tested?
After cloning the repo, setting up virtualenv and installing the required requirements
RUN
`export FLASK_ENV=development`
`export FLASK_APP=run.py`
`flask run`

Using POSTMAN test the above endpoints
### What are the relevant pivotal tracker stories?
#161883389

### Screenshots (if appropriate)
![cancel_api](https://user-images.githubusercontent.com/7009215/48395543-a3589600-e728-11e8-92cb-643706339bc9.png)

2018-11-13 11:49 UTC, cosmas28 commented
Kindly fix the failing tests.

2018-11-13 12:13 UTC, cosmas28 requested changes

2018-11-13 12:13 UTC, cosmas28 commented on app/__init__.py
> +    # app.config.from_pyfile('config.py')
Kindly remove the commented codes which have no use here.

2018-11-13 12:13 UTC, cosmas28 commented on config.py
> +    "development" : Development,
Kindly use either single or double quotes throughout your code. Don't mix them.

2018-11-14 07:18 UTC, Bakley commented on app/__init__.py
> +    # app.config.from_pyfile('config.py')
Okay, all done

2018-11-14 07:19 UTC, Bakley commented on config.py
> +    "development" : Development,
Thank you all resolved

2018-11-15 10:03 UTC, merged